FROM node:20-alpine

WORKDIR /app

# Set environment variables for cache and tmp directories
ENV TMP_PATH=/app/tmp
ENV CACHE_PATH=/app/cache

# Create directories
RUN mkdir -p $TMP_PATH $CACHE_PATH

COPY package.json package-lock.json ./
RUN npm install --cache $CACHE_PATH --prefer-offline

COPY . .

EXPOSE 8001

CMD ["npm", "run", "dev", "--", "--port", "8001", "--host", "0.0.0.0"]