version: '3.8'

services:
  # Redis - For caching and pub/sub messaging between services
  redis:
    image: redis:7.4-alpine
    container_name: sound-forge-redis
    command: redis-server --appendonly yes --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sound-forge-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # PostgreSQL - Database for storing metadata
  postgres:
    image: postgres:15-alpine
    container_name: sound-forge-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=soundforge
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sound-forge-network

  # Supabase - Local development setup
  supabase-db:
    image: supabase/postgres:15.1.0.117
    container_name: sound-forge-supabase-db
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data
    networks:
      - sound-forge-network
      
  supabase-kong:
    image: kong:2.8.1
    container_name: sound-forge-supabase-kong
    ports:
      - "8000:8000"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong.yml
    volumes:
      - ./kong.yml:/kong.yml
    networks:
      - sound-forge-network

networks:
  sound-forge-network:
    name: sound-forge-network
    driver: bridge

volumes:
  redis_data:
    name: sound-forge-redis-data
  postgres_data:
    name: sound-forge-postgres-data
  supabase_data:
    name: sound-forge-supabase-data
  audio_data:
    name: sound-forge-audio-data