_format_version: "2.1"
_transform: true

services:
  - name: auth-v1
    url: http://auth:9999/verify
    routes:
      - name: auth-v1-route
        paths:
          - /auth/v1
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Authorization
            - Content-Type
            - Accept
            - Origin
            - User-Agent
            - DNT
            - Cache-Control
            - X-Mx-ReqToken
            - Keep-Alive
            - X-Requested-With
            - If-Modified-Since
            - X-Api-Key
            - X-Client-Info
          credentials: true
          max_age: 86400

  - name: rest-v1
    url: http://rest:3000/rpc
    routes:
      - name: rest-v1-route
        paths:
          - /rest/v1
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Authorization
            - Content-Type
            - Accept
            - Origin
            - User-Agent
            - DNT
            - Cache-Control
            - X-Mx-ReqToken
            - Keep-Alive
            - X-Requested-With
            - If-Modified-Since
            - X-Api-Key
            - X-Client-Info
          credentials: true
          max_age: 86400

  - name: meta
    url: http://meta:8080
    routes:
      - name: meta-route
        paths:
          - /pg

plugins:
  - name: key-auth
    config:
      key_names:
        - apikey
  - name: acl
    config:
      allow:
        - anon
        - service_role