# Dockerfile.gpu-base
FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y ffmpeg curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs gcc g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables for cache and tmp directories
ENV TMP_PATH=/app/tmp
ENV CACHE_PATH=/app/cache

# Create directories
RUN mkdir -p $TMP_PATH $CACHE_PATH

# Expose a default port
EXPOSE 3000
